class  FacialTissue {
public static void main(String Face[]){
	String brand = "Brand	Presto";
	String feature = "Special Feature	OBA Free";
	String skinType = "Skin Type	All";
	int sheetCount = 200;
	String material  = "Paper";
    System.out.println("Name of the Brand" + brand);
	System.out.println("Name of the Feature " + feature );
	System.out.println("Skin Type" + skinType);
	System.out.println("Number of Sheet Count" + sheetCount);
	System.out.println("Nmae of the Material" + material );
}
}

	
	
