class FanSpeedExecutor{
public static void main (String Fan[])
{
FanSpeed.onOrOff();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.decreaseSpeed();
FanSpeed.increaseSpeed();
FanSpeed.onOrOff();
}
}