class MicrowaveExecutor{
public static void main (String LG[])
{
MicroWave.onOrOff();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.increaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.decreaseTemp();
MicroWave.increaseTemp();
MicroWave.onOrOff();
}
}
