class MixerSpeedExecutor{
public static void main (String Remote[])
{
MixerSpeed.onOrOff();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.decreaseSpeed();
MixerSpeed.increaseSpeed();
MixerSpeed.onOrOff();
}
}