class SwiggyExecutor{
public static void main(String foodDelivery[]){
System.out.println("main started");
double cost = Swiggy.look("Chocolate Cake");
System.out.println("The Price for Chocolate Cake of 500Gm is "+cost);
double costWithQuantity = Swiggy.look("Chocolate Cake",2);
System.out.println("The Price for Chocolate Cake of 500Gm is "+costWithQuantity);
double cost1 = Swiggy.look("Tava Paneer Roll");
System.out.println("The Price for Tava Paneer Rollis "+cost1);
double costWithQuantity1 = Swiggy.look("Tava Paneer Roll",3);
System.out.println("The Price for Tava Paneer Rollis "+costWithQuantity1);
double cost2 = Swiggy.look("Gourmet Falafel Burger");
System.out.println("The Price for Gourmet Falafel Burger is "+cost2);
double costWithQuantity2 = Swiggy.look("Gourmet Falafel Burger",4);
System.out.println("The Price for Gourmet Falafel Burger is "+costWithQuantity2);
double cost3 = Swiggy.look("Garlic Fried Rice");
System.out.println("The Price for Garlic Fried Rice is "+cost3);
double costWithQuantity3 = Swiggy.look("Garlic Fried Rice",5);
System.out.println("The Price for Garlic Fried Rice is "+costWithQuantity3);
double cost4 = Swiggy.look("Yaki Udon Veg Noodles");
System.out.println("The Price for Yaki Udon Veg Noodles is "+cost4);
double costWithQuantity4 = Swiggy.look("Yaki Udon Veg Noodles",7);
System.out.println("The Price for Yaki Udon Veg Noodles is "+costWithQuantity4);
double cost5 = Swiggy.look("Hibachi Rice");
System.out.println("The Price for Hibachi Rice is "+cost5);
double costWithQuantity5 = Swiggy.look("Hibachi Rice",2);
System.out.println("The Price for Hibachi Rice is "+costWithQuantity5);
double cost6 = Swiggy.look("Vietnamese Veg Dumpling");
System.out.println("The Price for Vietnamese Veg Dumpling is "+cost6);
double costWithQuantity6 = Swiggy.look("Vietnamese Veg Dumpling",3);
System.out.println("The Price for Vietnamese Veg Dumpling is "+costWithQuantity6);
double cost7 = Swiggy.look("Jammu Ka Rajma Rice Bowl");
System.out.println("The Price for Jammu Ka Rajma Rice Bowl is "+cost7);
double costWithQuantity7 = Swiggy.look("Jammu Ka Rajma Rice Bowl",5);
System.out.println("The Price for Jammu Ka Rajma Rice Bowl is "+costWithQuantity7);
double cost8 = Swiggy.look("Jaggery Rosogalla");
System.out.println("The Price for Jaggery Rosogalla is "+cost8);
double costWithQuantity8 = Swiggy.look("Jaggery Rosogalla",2);
System.out.println("The Price for Jaggery Rosogalla is "+costWithQuantity8);
double cost9 = Swiggy.look("Lava Cake");
System.out.println("The Price for Lava Cake is "+cost9);
double costWithQuantity9 = Swiggy.look("Lava Cake",5);
System.out.println("The Price for Lava Cake is "+costWithQuantity9);
double cost10 = Swiggy.look("Herbed Garlic Chicken Sandwich");
System.out.println("The Price for Herbed Garlic Chicken Sandwich is "+cost10);
double costWithQuantity10 = Swiggy.look("Herbed Garlic Chicken Sandwich",3);
System.out.println("The Price for Herbed Garlic Chicken Sandwich is "+costWithQuantity10);
double cost11 = Swiggy.look("Tiramisu Frappe Coffee Flavoured Chocolate MilkShake");
System.out.println("The Price for Tiramisu Frappe Coffee Flavoured Chocolate MilkShake is "+cost11);
double costWithQuantity11 = Swiggy.look("Tiramisu Frappe Coffee Flavoured Chocolate MilkShake",2);
System.out.println("The Price for Tiramisu Frappe Coffee Flavoured Chocolate MilkShake is "+costWithQuantity11);
double cost12 = Swiggy.look("Vampire Slayer Shroom Pizza");
System.out.println("The Price for Vampire Slayer Shroom Pizza is "+cost12);
double costWithQuantity12 = Swiggy.look("Vampire Slayer Shroom Pizza",4);
System.out.println("The Price for Vampire Slayer Shroom Pizza is "+costWithQuantity12);
double cost13 = Swiggy.look("Veg Falafel Wrap");
System.out.println("The Price for Veg Falafel Wrap is "+cost13);
double costWithQuantity13 = Swiggy.look("Veg Falafel Wrap",6);
System.out.println("The Price for Veg Falafel Wrap is "+costWithQuantity13);
double cost14 = Swiggy.look("Toasted Pita With Hummus");
System.out.println("The Price for Toasted Pita With Hummus is "+cost14);
double costWithQuantity14 = Swiggy.look("Toasted Pita With Hummus",3);
System.out.println("The Price for Toasted Pita With Hummus is "+costWithQuantity14);
double cost15 = Swiggy.look("Pita Pocket Panner");
System.out.println("The Price for Pita Pocket Panner is "+cost15);
double costWithQuantity15 = Swiggy.look("Pita Pocket Panner",3);
System.out.println("The Price for Pita Pocket Panner is "+costWithQuantity15);
double cost16 = Swiggy.look("Iced Americano");
System.out.println("The Price for Chocolate Cake of 500Gm is "+cost16);
double costWithQuantity16 = Swiggy.look("Iced Americano",8);
System.out.println("The Price for Chocolate Cake of 500Gm is "+costWithQuantity16);
double cost17 = Swiggy.look("Cappuccino");
System.out.println("The Price for Cappuccino is "+cost17);
double costWithQuantity17 = Swiggy.look("Cappuccino",2);
System.out.println("The Price for Cappuccino is "+costWithQuantity17);
double cost18 = Swiggy.look("Energizer");
System.out.println("The Price for Energizer is "+cost18);
double costWithQuantity18 = Swiggy.look("Energizer",4);
System.out.println("The Price for Energizer is "+costWithQuantity18);
double cost19 = Swiggy.look("Virgin Pina Colada");
System.out.println("The Price for Virgin Pina Colada is "+cost19);
double costWithQuantity19 = Swiggy.look("Virgin Pina Colada",3);
System.out.println("The Price for Virgin Pina Colada is "+costWithQuantity19);
double cost20 = Swiggy.look("Classic Mac and Cheese");
System.out.println("The Price for Classic Mac and Cheese is "+cost20);
double costWithQuantity20 = Swiggy.look("Classic Mac and Cheese",4);
System.out.println("The Price for Classic Mac and Cheese is "+costWithQuantity20);
double cost21 = Swiggy.look("Spaghetti Aglio e olio peperoncino");
System.out.println("The Price for Spaghetti Aglio e olio peperoncino is "+cost21);
double costWithQuantity21 = Swiggy.look("Spaghetti Aglio e olio peperoncino",2);
System.out.println("The Price for Spaghetti Aglio e olio peperoncino is "+costWithQuantity21);
double cost22 = Swiggy.look("Italian arrabbiata");
System.out.println("The Price for Italian arrabbiata is "+cost22);
double costWithQuantity22 = Swiggy.look("Italian arrabbiata",4);
System.out.println("The Price for Italian arrabbiata is "+costWithQuantity22);
double cost23 = Swiggy.look("Tres leches");
System.out.println("The Price for Tres leches is "+cost23);
double costWithQuantity23 = Swiggy.look("Tres leches",5);
System.out.println("The Price for Tres leches is "+costWithQuantity23);
double cost24 = Swiggy.look("Chilli hicken bao");
System.out.println("The Price for Chilli hicken bao is "+cost24);
double costWithQuantity24 = Swiggy.look("Chilli hicken bao",1);
System.out.println("The Price for Chilli hicken bao is "+costWithQuantity24);
double cost25 = Swiggy.look("Handi ka Bhuna Murg&Laccha Paratha");
System.out.println("The Price for Handi ka Bhuna Murg&Laccha Paratha is "+cost25);
double costWithQuantity25 = Swiggy.look("Handi ka Bhuna Murg&Laccha Paratha",3);
System.out.println("The Price for Handi ka Bhuna Murg&Laccha Paratha is "+costWithQuantity25);
double cost26 = Swiggy.look("Murg dum biriyani");
System.out.println("The Price for Murg dum biriyani is "+cost26);
double costWithQuantity26 = Swiggy.look("Murg dum biriyani",2);
System.out.println("The Price for Murg dum biriyani is "+costWithQuantity26);
double cost27 = Swiggy.look("Classic Chicken Tikka");
System.out.println("The Price for Classic Chicken Tikka is "+cost27);
double costWithQuantity27 = Swiggy.look("Classic Chicken Tikka",2);
System.out.println("The Price for Classic Chicken Tikka is "+costWithQuantity27);
double cost28 = Swiggy.look("Butter Pav Bhaji");
System.out.println("The Price for Butter Pav Bhaji is "+cost28);
double costWithQuantity28 = Swiggy.look("Butter Pav Bhaji",3);
System.out.println("The Price for Butter Pav Bhaji is "+costWithQuantity28);
double cost29 = Swiggy.look("Tawa Pulao");
System.out.println("The Price for Tawa Pulao is "+cost29);
double costWithQuantity29 = Swiggy.look("Tawa Pulao",2);
System.out.println("The Price for Tawa Pulao is "+costWithQuantity29);
double cost30 = Swiggy.look("Jalebi");
System.out.println("The Price for Jalebi of 500 Gm is "+cost30);
double costWithQuantity30 = Swiggy.look("Jalebi",3);
System.out.println("The Price for Jalebi of 500 Gm is "+costWithQuantity30);
double cost31 = Swiggy.look("Mushroom Pepper Dry");
System.out.println("The Price for Mushroom Pepper Dry is "+cost31);
double costWithQuantity31 = Swiggy.look("Mushroom Pepper Dry",3);
System.out.println("The Price for Mushroom Pepper Dry is "+costWithQuantity31);
double cost32 = Swiggy.look("Channa Bhatura");
System.out.println("The Price for Channa Bhatura is "+cost32);
double costWithQuantity32 = Swiggy.look("Channa Bhatura",2);
System.out.println("The Price for Channa Bhatura is "+costWithQuantity32);
double cost33 = Swiggy.look("Schezwan Fried Rice");
System.out.println("The Price for Schezwan Fried Rice is "+cost33);
double costWithQuantity33 = Swiggy.look("Schezwan Fried Rice",5);
System.out.println("The Price for Schezwan Fried Rice is "+costWithQuantity33);
double cost34 = Swiggy.look("Sweet Corn Soup");
System.out.println("The Price for Sweet Corn Soup is "+cost34);
double costWithQuantity34 = Swiggy.look("Sweet Corn Soup",4);
System.out.println("The Price for Sweet Corn Soup is "+costWithQuantity34);
double cost35 = Swiggy.look("Aloo Jeera");
System.out.println("The Price for Aloo Jeera is "+cost35);
double costWithQuantity35 = Swiggy.look("Aloo Jeera",2);
System.out.println("The Price for Aloo Jeera is "+costWithQuantity35);
double cost36 = Swiggy.look("Dal Tadka Khichdi");
System.out.println("The Price for Dal Tadka Khichdi is "+cost36);
double costWithQuantity36 = Swiggy.look("Dal Tadka Khichdi",4);
System.out.println("The Price for Dal Tadka Khichdi is "+costWithQuantity36);
double cost37 = Swiggy.look("Naked Nutella Waffle");
System.out.println("The Price for Naked Nutella Waffle is "+cost37);
double costWithQuantity37 = Swiggy.look("Naked Nutella Waffle",2);
System.out.println("The Price for Naked Nutella Waffle is "+costWithQuantity37);
double cost38 = Swiggy.look("Fish Fry");
System.out.println("The Price for Fish Fry is "+cost38);
double costWithQuantity38 = Swiggy.look("Fish Fry");
System.out.println("The Price for Fish Fry is "+costWithQuantity38);
double cost39 = Swiggy.look("Vada");
System.out.println("The Price for Vada is "+cost39);
double costWithQuantity39 = Swiggy.look("Vada",2);
System.out.println("The Price for Vada is "+costWithQuantity39);
double cost40 = Swiggy.look("Meaty Omelette");
System.out.println("The Price for Meaty Omelette is "+cost40);
double costWithQuantity40 = Swiggy.look("Meaty Omelette",2);
System.out.println("The Price for Meaty Omelette is "+costWithQuantity40);
double cost41 = Swiggy.look("Egg Roast");
System.out.println("The Price for Egg Roast is "+cost41);
double costWithQuantity41 = Swiggy.look("Egg Roast",4);
System.out.println("The Price for Egg Roast is "+costWithQuantity41);
double cost42 = Swiggy.look("Mutton Nihari");
System.out.println("The Price for Mutton Nihari is "+cost42);
double costWithQuantity42 = Swiggy.look("Mutton Nihari",5);
System.out.println("The Price for Mutton Nihari is "+costWithQuantity42);
double cost43 = Swiggy.look("Wheat Laccha Paratha");
System.out.println("The Price for Wheat Laccha Paratha is "+cost43);
double costWithQuantity43 = Swiggy.look("Wheat Laccha Paratha",2);
System.out.println("The Price for Wheat Laccha Paratha is "+costWithQuantity43);
double cost44 = Swiggy.look("Brewski Signature nachos");
System.out.println("The Price for Brewski Signature nachos is "+cost44);
double costWithQuantity44 = Swiggy.look("Brewski Signature nachos",4);
System.out.println("The Price for Brewski Signature nachos is "+costWithQuantity44);
double cost45 = Swiggy.look("Masala Dosa");
System.out.println("The Price for Masala Dosa is "+cost45);
double costWithQuantity45 = Swiggy.look("Masala Dosa",2);
System.out.println("The Price for Masala Dosa is "+costWithQuantity45);
double cost46 = Swiggy.look("Jeera Rice");
System.out.println("The Price for Jeera Rice is "+cost46);
double costWithQuantity46 = Swiggy.look("Jeera Rice",4);
System.out.println("The Price for Jeera Rice is "+costWithQuantity46);
double cost47 = Swiggy.look("Ghobi Manchurian");
System.out.println("The Price for Ghobi Manchurian is "+cost47);
double costWithQuantity47 = Swiggy.look("Ghobi Manchurian",5);
System.out.println("The Price for Ghobi Manchurian is "+costWithQuantity47);
double cost48 = Swiggy.look("Alu Bonda");
System.out.println("The Price for Alu Bonda is "+cost48);
double costWithQuantity48 = Swiggy.look("Alu Bonda",1);
System.out.println("The Price for Alu Bonda is "+costWithQuantity48);
double cost49 = Swiggy.look("Jeera Rice");
System.out.println("The Price for Jeera Rice is "+cost49);
double costWithQuantity49 = Swiggy.look("Jeera Rice",5);
System.out.println("The Price for GJeera Rice is "+costWithQuantity49);
double cost50 = Swiggy.look("Ghobi Manchurian");
System.out.println("The Price for Ghobi Manchurian is "+cost50);
double costWithQuantity50 = Swiggy.look("Ghobi Manchurian",5);
System.out.println("The Price for Ghobi Manchurian is "+costWithQuantity50);
System.out.println("Main ended" );
}
}