class ZomatoExecutor {
public static void main(String foodDelivery[]){
System.out.println("main started");
Zomato.look("Chocolate Cake");
Zomato.look("Tava Paneer Roll");
Zomato.look("Gourmet Falafel Burger");
Zomato.look("Garlic Fried Rice");
Zomato.look("Yaki Udon Veg Noodles");
Zomato.look("Hibachi Rice");
Zomato.look("Vietnamese Veg Dumpling");
Zomato.look("Jammu Ka Rajma Rice Bowl");
Zomato.look("Jaggery Rosogalla");
Zomato.look("Lava Cake");
Zomato.look("Herbed Garlic Chicken Sandwich");
Zomato.look("Tiramisu Frappe Coffee Flavoured Chocolate MilkShake");
Zomato.look("Vampire Slayer Shroom Pizza");
Zomato.look("Iced Americano");
Zomato.look("Veg Falafel Wrap");
Zomato.look("Toasted Pita With Hummus");
Zomato.look("Pita Pocket Panner");
Zomato.look("Iced Americano");
Zomato.look("Cappuccino");
Zomato.look("Energizer");
Zomato.look("Virgin Pina Colada");
Zomato.look("Classic Mac and Cheese");
Zomato.look("Spaghetti Aglio e olio peperoncino");
Zomato.look("Italian arrabbiata");
Zomato.look("Tres leches");
Zomato.look("Chilli hicken bao");
Zomato.look("Handi ka Bhuna Murg&Laccha Paratha");
Zomato.look("Murg dum biriyani");
Zomato.look("Classic Chicken Tikka");
Zomato.look("Butter Pav Bhaji");
Zomato.look("Tawa Pulao");
Zomato.look("Jalebi");
Zomato.look("Mushroom Pepper Dry");
Zomato.look("Channa Bhatura");
Zomato.look("Schezwan Fried Rice");
Zomato.look("Sweet Corn Soup");
Zomato.look("Aloo Jeera");
Zomato.look("Dal Tadka Khichdi");
Zomato.look("Naked Nutella Waffle");
Zomato.look("Fish Fry");
Zomato.look("vada");
Zomato.look("Meaty Omelette");
Zomato.look("Egg Roast");
Zomato.look("Mutton Nihari");
Zomato.look("Wheat Laccha Paratha");
Zomato.look("Brewski Signature nachos");
Zomato.look("Masala Dosa");
Zomato.look("Jeera Rice");
Zomato.look("Ghobi Manchurian");
System.out.println("Main ended" );
}
}